// <auto-generated />
using BookyStore.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookyStore.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240114030826_seedBangTheLoai")]
    partial class seedBangTheLoai
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookyStore.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("TheLoai");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Hài hước"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Kinh dị"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Tình cảm"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Lịch sử"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
